name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_SECRET }}
      - name: Docker Registry Log in
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DO_HUB_USER }}
          password: ${{ secrets.DO_HUB_PW }}

      - name: Build and Push Web
        id: build-push-web
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./ci/Dockerfile
          push: true
          tags: gagal1818/kiii/lab3:latest

      - name: Copy docker-compose.yml to the remote server
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.DO_USER }}@${{ secrets.DO_IP }}:/var/docker/kiii/lab3/docker-compose.yml
      - name: Pull and Start the container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_IP }} << 'EOF'
            cd /var/docker/kiii/lab3
            docker-compose pull  
            docker-compose down
            docker-compose up -d 
          EOF